// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TPfMtxZ_71wZLKi5IaVuLo487F9J4cE',
    appId: '1:1082311197625:web:c5f83e23cb3b816bb62c68',
    messagingSenderId: '1082311197625',
    projectId: 'gasguard-d1139',
    authDomain: 'gasguard-d1139.firebaseapp.com',
    storageBucket: 'gasguard-d1139.firebasestorage.app',
    measurementId: 'G-4T2SBYL46V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvB23eSdHoLNnUSE1TMBapAsh6sAxxjiM',
    appId: '1:1082311197625:android:8c2993daa63a3c74b62c68',
    messagingSenderId: '1082311197625',
    projectId: 'gasguard-d1139',
    storageBucket: 'gasguard-d1139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPrEd64MOy2c40arww0TWXqTcliKuFUI',
    appId: '1:1082311197625:ios:c8ed22133f374239b62c68',
    messagingSenderId: '1082311197625',
    projectId: 'gasguard-d1139',
    storageBucket: 'gasguard-d1139.firebasestorage.app',
    iosBundleId: 'com.example.gasguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfPrEd64MOy2c40arww0TWXqTcliKuFUI',
    appId: '1:1082311197625:ios:c8ed22133f374239b62c68',
    messagingSenderId: '1082311197625',
    projectId: 'gasguard-d1139',
    storageBucket: 'gasguard-d1139.firebasestorage.app',
    iosBundleId: 'com.example.gasguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TPfMtxZ_71wZLKi5IaVuLo487F9J4cE',
    appId: '1:1082311197625:web:bdac1c9b76a50d9fb62c68',
    messagingSenderId: '1082311197625',
    projectId: 'gasguard-d1139',
    authDomain: 'gasguard-d1139.firebaseapp.com',
    storageBucket: 'gasguard-d1139.firebasestorage.app',
    measurementId: 'G-H7MLBE079J',
  );
}
